### ISSUE TITLE
Рекомендую добавить у всех файлах defined('COT_CODE') or die('Wrong URL');

### ISSUE THREAD

**Issue by CrazyFreeMan** [AlteraWeb/AlterFolio#1]
Не нужно осталять дыры в плагине :)

**Comment by AlteraWeb** [comment]
какие дыры?

24.03.2015, 18:34, "Yaroslav" notifications@github.com:

**Comment by CrazyFreeMan** [comment]
Да вот в [нескольких файлах](https://github.com/AlteraWeb/AlterFolio/blob/master/alterfolio/alterfolio.folio.tags.php#L16) не идет проверка на наличие констант 

```
defined('COT_CODE') or die('Wrong URL');
```

Они для того чтоб не вызывать файл там где не нужно

**Comment by AlteraWeb** [comment]
Спасибо,  исправлю.
Это был мой первый плагин )) 

24.03.2015, 18:39, "Yaroslav" notifications@github.com:

**Comment by CrazyFreeMan** [comment]
fixed 21f00388ab3068439425dce6b8d68b7e5176f634 1fdf669b2b27f2fd5cc4cea9a9b601a7137179f9
